### ISSUE TITLE
Can you describe the parameters? thank you

### ISSUE THREAD

**Issue by vanphong97** [donghao51/laser-docking#1]
I am not understanding all the parameters (tri_len, angleDif, disDif, threshold) in node "laser_split_and_merge_trans". can you help me understand it?

**Comment by donghao51** [comment]
Please see
https://github.com/donghao51/laser-docking/blob/369031b14f888bf42a9d9085069524331bbfc9e1/src/parameters_description.txt#L13

**Comment by vanphong97** [comment]
thank you. my robot was able to find landmarks
can you describe the parameters in laser_dock.launch file?

**Comment by donghao51** [comment]
kp and kd are PID parameters. laser2base is the transform between lidar and robot base in the front direction. linearV and angleV are the velocity limits. yDesire is the desired docking distance to the landmark center and dis_to_mid_err is the tolerance for this distance.

**Comment by vanphong97** [comment]
what are the parameters "goal_x", "goal_y", "goal_dir" ?. thank you

**Comment by donghao51** [comment]
they are goal positions and orientation
